= Istio Security Mission

== Purpose
Showcase Istio TLS and ACL via a set of Spring Boot applications.

== Prerequisites
. Openshift 3.10 cluster
. Istio 1.0.x installed on the aforementioned cluster using the link:https://github.com/Maistra/istio-operator[Istio Operator].
.. Follow link:https://github.com/Maistra/openshift-ansible/blob/maistra-0.1.0-ocp-3.1.0-istio-1.0.0/istio/Installation.md[these] instructions for more information about the Operator
. Login to the cluster with the *admin* user

== Environment preparation

Create a new project/namespace on the cluster. This is where your application will be deployed.

```bash
oc new-project <whatever valid project name you want>
```

== Build and deploy the application
=== With Fabric8 Maven Plugin (FMP)
Execute the following command to build the project and deploy it to OpenShift:
```bash
mvn clean fabric8:deploy -Popenshift
```
Configuration for FMP may be found both in pom.xml and `src/main/fabric8` files/folders.

This configuration is used to define service names and deployments that control how pods are labeled/versioned on the OpenShift cluster.

=== With Source to Image build (S2I)
Run the following commands to apply and execute the OpenShift templates that will configure and deploy the applications:
```bash
find . | grep openshiftio | grep application | xargs -n 1 oc apply -f

oc new-app --template=spring-boot-istio-security-name -p SOURCE_REPOSITORY_URL=https://github.com/snowdrop/spring-boot-istio-security-booster -p SOURCE_REPOSITORY_REF=master -p SOURCE_REPOSITORY_DIR=spring-boot-istio-security-name
oc new-app --template=spring-boot-istio-security-greeting -p SOURCE_REPOSITORY_URL=https://github.com/snowdrop/spring-boot-istio-security-booster -p SOURCE_REPOSITORY_REF=master -p SOURCE_REPOSITORY_DIR=spring-boot-istio-security-greeting
```

== Configure Istio gateway
This application uses v1alpha3 routing API. Execute the following command to configure gateway and virtual service:
```bash
oc apply -f rules/gateway.yml
```

= Use Cases
== Scenario #1. Mutual TLS

This scenario demonstrates a mutual transport level security between the services.

1. Open the booster’s web page via Istio gateway route
+
```bash
echo http://$(oc get route istio-ingressgateway -o jsonpath='{.spec.host}{"\n"}' -n istio-system)/
```
1. "Hello, World!" should be returned after invoking `greeting` service.
1. Now modify greeting deployment to disable sidecar injection by replacing both `sidecar.istio.io/inject` values to `false`
+
```bash
oc edit deploymentconfigs/spring-boot-istio-security-greeting
```
1. Open the booster’s web page via `greeting` service’s route
+
```bash
echo http://$(oc get route spring-boot-istio-security-greeting -o jsonpath='{.spec.host}{"\n"}' -n $(oc project -q))/
```
1. `Greeting` service invocation will fail with a reset connection, because the `greeting` service has to be inside a service mesh in order to access the `name` service.
1. Cleanup by setting `sidecar.istio.io/inject` values to true
+
```bash
oc edit deploymentconfigs/spring-boot-istio-security-greeting
```

== Scenario #2. Access control

This scenario demonstrates access control when using mutual TLS. In order to access a name service, calling service has to have a specific label and service account name.

1. Open the booster’s web page via Istio gateway route
+
```bash
echo http://$(oc get route istio-ingressgateway -o jsonpath='{.spec.host}{"\n"}' -n istio-system)/
```
1. "Hello, World!" should be returned after invoking `greeting` service.
1. Configure Istio Mixer to block `greeting` service from accessing `name` service
+
```bash
oc apply -f rules/block-greeting-service.yml
```
1. `Greeting` service invocations to the `name` service will be forbidden.
1. Configure Istio Mixer to only allow requests from `greeting` service and with `sa-greeting` service account to access `name` service
+
```bash
oc apply -f <(sed -e "s/TARGET_NAMESPACE/$(oc project -q)/g" rules/require-service-account-and-label.yml)
```
1. "Hello, World!" should be returned after invoking `greeting` service.
1. Cleanup
+
```bash
oc delete -f rules/require-service-account-and-label.yml
```

== Remove gateway configuration
```bash
oc delete -f rules/gateway.yml
```

== Undeploy the application

=== With Fabric8 Maven Plugin (FMP)
```bash
mvn fabric8:undeploy
```

=== With Source to Image build (S2I)
```bash
oc delete all --all
find . | grep openshiftio | grep application | xargs -n 1 oc delete -f
```

=== Remove the namespace
This will delete the project from the OpenShift cluster
```bash
oc delete project <your project name>
```

== Integration tests

To run integration tests, create a new namespace and run maven job
```bash
oc new-project <project-name>
mvn clean verify -Popenshift,openshift-it
```
