apiVersion: "config.istio.io/v1alpha2"
kind: denier
metadata:
  name: denynameservicehandler
spec:
  status:
    code: 7
    message: Not allowed
---
apiVersion: "config.istio.io/v1alpha2"
kind: checknothing
metadata:
  name: denynameservicerequest
spec:
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: denynameserviceaccess
spec:
  match: destination.labels["app"] == "spring-boot-istio-security-name" && source.labels["app"] == "spring-boot-istio-security-greeting"
  actions:
  - handler: denynameservicehandler.denier
    instances: [ denynameservicerequest.checknothing ]